name: Selenium Scraper (Every 15 Minutes)

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager pandas

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Scraper
        run: python Scraping-pickle-car-automation/pickle-scrapp.py

      - name: Upload Scraped Data (For Logging)
        uses: actions/upload-artifact@v4  # Use v4 instead of v3
        with:
          name: scraped-data
          path: scraper.log
